version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: challenge_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_db
    ports:
      - "5432:5432"

